#!/usr/bin/env python3

def main():
    rl = int(sys.argv[1])
    td = float(sys.argv[2])
    theta = float(sys.argv[3])
    genome = sys.argv[4]
    out_stem = sys.argv[5]

    print(f"read_len :{rl}")
    print(f"target_depth :{td}")
    print(f"theta :{theta}")
    print(f"genome :{genome}")
    print(f"out_stem :{out_stem}")